### ISSUE TITLE
Neutral playing location

### ISSUE THREAD

**Issue by szabozoltan69** [marcoblume/pinnacle.API#1]
It would be fine to get the information (via Pinnacle API) if a match is played on a neutral location. On s.likesport.com there is a letter "[N]" after the home team name where "home" team is not a really home team (because of a neutrally located match).

There is a HomeTeamType property (Team1/Team2) but this is not the same.

**Comment by marcoblume** [comment]
Usually it will be indicated with a (n) behind the team name but it might have been overlooked  in your case.
