### ISSUE TITLE
Functions with errors

### ISSUE THREAD

**Issue by tiagoafonso85** [marcoblume/pinnacle.API#10]
Hi,

Thank you for providing this wrapper for the Pinnacle API.

I started testing Pinnacle.API from GitHub on Linux and found this functions with this issues:

In GetLine () I can not get any result, even varying the arguments, as follows:

> GetLine(sportid=29,leagueids=9097,eventid=727277730,periodnumber=0,team="Team1",betType="SPREAD",handicap=0,oddsFormat="DECIMAL")
No encoding supplied: defaulting to UTF-8.

> GetLine(sportid=29,leagueids=9097,eventid=727277730,handicap=2.5,periodnumber=0,team="TEAM1",betType="TOTAL_POINTS",side="OVER",oddsFormat="DECIMAL")
No encoding supplied: defaulting to UTF-8.

In GetPassword():

> GetPassword()
Error: could not find function "GetPassword"

In GetSpecialOdds() with the argument "wide":

> GetSpecialOdds(sportid=29,tableformat="wide")

I receive:

Very Data...
    ...
    ... 
    ... And
    Warning messages:
1: In `[.data.table`(out, , `:=`(nullcol, NULL)) :
  Adding new column 'nullcol' then assigning NULL (deleting it).
2: In `[.data.table`(out, , `:=`(altLineId, NULL)) :
  Adding new column 'altLineId' then assigning NULL (deleting it).
3: In as.data.table.list(jval) :
  Item 1 is of size 32 but maximum size is 119 (recycled leaving a remainder of 23 items)
4: In as.data.table.list(jval) :
  Item 2 is of size 32 but maximum size is 119 (recycled leaving a remainder of 23 items)
5: In as.data.table.list(jval) :
  Item 3 is of size 32 but maximum size is 119 (recycled leaving a remainder of 23 items)
6: In as.data.table.list(jval) :
  Item 4 is of size 32 but maximum size is 119 (recycled leaving a remainder of 23 items)
7: In as.data.table.list(jval) :
  Item 5 is of size 32 but maximum size is 119 (recycled leaving a remainder of 23 items)

Thanks

**Comment by shapenaji** [comment]
Hello!

Per GetLine, it seems the function is returning the value invisibly, (if you store the value to an intermediate variable and then check the value, you'll see it's returning content.)
You can still program against this, but I'll make a note to fix visible content.

GetPassword is unexported as of 2.0.4 on CRAN, credentials are now stored encrypted in package namespace. The password is no longer immediately available by an exported function. Is there a reason you need the password? `pinnacle.API:::GetPassword()` works, but I can't guarantee stability with that going forward.

I'll take a look at GetSpecialOdds, we shouldn't be receiving those warnings.

**Comment by shapenaji** [comment]
Version 2.0.7 here on github should fix your issues. The easiest way to install the github version is with devtools:

`devtools::install_github('marcoblume/pinnacle.API')`

**Comment by tiagoafonso85** [comment]
Hi Shape,


Thanks very much for the quick fix.


There is no reason to use the password, just thought it was helping by sharing all the flaws it had encountered.

Everything's fine now. Only GetSpecialOdds is giving even more mistakes this time around. But I think it's okay, I can still program against this, I think.

GetSpecialOdds (sportid = 29, tableformat = "wide")

Data...
...
...

There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In as.data.table.list(jval) :
  Item 6 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
2: In as.data.table.list(jval) :
  Item 7 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
3: In as.data.table.list(jval) :
  Item 8 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
4: In as.data.table.list(jval) :
  Item 9 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
5: In as.data.table.list(jval) :
  Item 10 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
6: In as.data.table.list(jval) :
  Item 11 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
7: In as.data.table.list(jval) :
  Item 12 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
8: In as.data.table.list(jval) :
  Item 13 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
9: In as.data.table.list(jval) :
  Item 14 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
10: In as.data.table.list(jval) :
  Item 15 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
11: In as.data.table.list(jval) :
  Item 16 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
12: In as.data.table.list(jval) :
  Item 17 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
13: In as.data.table.list(jval) :
  Item 18 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
14: In as.data.table.list(jval) :
  Item 19 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
15: In as.data.table.list(jval) :
  Item 20 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
16: In as.data.table.list(jval) :
  Item 21 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
17: In as.data.table.list(jval) :
  Item 22 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
18: In as.data.table.list(jval) :
  Item 23 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
19: In as.data.table.list(jval) :
  Item 24 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
20: In as.data.table.list(jval) :
  Item 25 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
21: In as.data.table.list(jval) :
  Item 26 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
22: In as.data.table.list(jval) :
  Item 27 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
23: In as.data.table.list(jval) :
  Item 28 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
24: In as.data.table.list(jval) :
  Item 29 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
25: In as.data.table.list(jval) :
  Item 30 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
26: In as.data.table.list(jval) :
  Item 31 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
27: In as.data.table.list(jval) :
  Item 32 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
28: In as.data.table.list(jval) :
  Item 33 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
29: In as.data.table.list(jval) :
  Item 34 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
30: In as.data.table.list(jval) :
  Item 35 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
31: In as.data.table.list(jval) :
  Item 36 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
32: In as.data.table.list(jval) :
  Item 37 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
33: In as.data.table.list(jval) :
  Item 38 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
34: In as.data.table.list(jval) :
  Item 39 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
35: In as.data.table.list(jval) :
  Item 40 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
36: In as.data.table.list(jval) :
  Item 41 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
37: In as.data.table.list(jval) :
  Item 42 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
38: In as.data.table.list(jval) :
  Item 43 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
39: In as.data.table.list(jval) :
  Item 44 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
40: In as.data.table.list(jval) :
  Item 45 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
41: In as.data.table.list(jval) :
  Item 46 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
42: In as.data.table.list(jval) :
  Item 47 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
43: In as.data.table.list(jval) :
  Item 48 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
44: In as.data.table.list(jval) :
  Item 49 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
45: In as.data.table.list(jval) :
  Item 50 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
46: In as.data.table.list(jval) :
  Item 51 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
47: In as.data.table.list(jval) :
  Item 52 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
48: In as.data.table.list(jval) :
  Item 53 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
49: In as.data.table.list(jval) :
  Item 54 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)
50: In as.data.table.list(jval) :
  Item 55 is of size 35 but maximum size is 49 (recycled leaving a remainder of 14 items)



I have all my whole operating system updated, including R and their packages ...

Thanks

________________________________
De: Shape <notifications@github.com>
Enviado: segunda-feira, 29 de maio de 2017 09:51:21
Para: marcoblume/pinnacle.API
Cc: tiagoafonso85; Author
Assunto: Re: [marcoblume/pinnacle.API] Functions with errors (#10)


Version 2.0.7 here on github should fix your issues. The easiest way to install the github version is with devtools:

devtools::install_github('marcoblume/pinnacle.API')

**Comment by shapenaji** [comment]
Hi Tiago,

released a second fix, see if that returns what you're after.

The first fix exposed a second issue. I'm not receiving any more warnings now though.

Let me know if it fixes your issue!

**Comment by tiagoafonso85** [comment]
Hi Shape,

It's fixed. No warnings...

Thanks
