### ISSUE TITLE
invalid char in json text.

### ISSUE THREAD

**Issue by jcr-lyxor** [marcoblume/pinnacle.API#11]
Hello,
I get an error maybe fom fromJson : 

```
No encoding supplied: defaulting to UTF-8.
Error: lexical error: invalid char in json text.
                                       <!doctype html public "-//w3c//
                     (right here) ------^

```
Any idea how to fix it?

**Comment by shapenaji** [comment]
Hi jcr-lyxor, 

can you give a reproducible example?

if you're continuing to get that error, it may be that you're not able to access the API from your location. The API does not work in all countries.

**Comment by jcr-lyxor** [comment]
Hello,

Yes indeed you are right. Thank you
