### ISSUE TITLE
GetInrunning()

### ISSUE THREAD

**Issue by AADias** [marcoblume/pinnacle.API#12]
Hi,

I am using the latest version of R Studio with the the Pinnacle.API and the code GetInrunning() doesn't work for me. Also I am using R 3.4.1

What I get is below.

thanks

> library (pinnacle.API)
Warning message:
package ‘pinnacle.API’ was built under R version 3.3.3 
> SetAPIEndpoint("https://api.pinnaclesports.com")
Package endpoint changed to: https://api.pinnaclesports.com
> SetCredentials("xxxxxxx", "xxxxxx")  - xxx were put here just for my privacy
> AcceptTermsAndConditions(accepted=TRUE)
> GetInrunning()
No encoding supplied: defaulting to UTF-8.

**Comment by shapenaji** [comment]
Hi AADias,

It is actually returning the values, it's just returning them invisibly.

If you do:

`inrunning <- GetInrunning()`

and then print that, you should see it. If you're programming against it, it should have no impact. But this will be fixed in the next cran version.

**Comment by shapenaji** [comment]
Believe this is fixed in earlier release. if it comes back up, feel free to reopen
