### ISSUE TITLE
Unable to get sports

### ISSUE THREAD

**Issue by ggittu** [marcoblume/pinnacle.API#15]
This happens every time when I try to get sports, even though I am able to successfully login
> sport_data <- GetSports()
Pulling Sports
Error: lexical error: invalid char in json text.
                                       <!doctype html public "-//w3c//
                     (right here) ------^

**Comment by shapenaji** [comment]
hi ggittu,

That's an error that typically happens when the API is not available from your location. (See README)

You're able to login to the website though?

**Comment by shapenaji** [comment]
Closing for now, will reopen if that did not clarify.
