### ISSUE TITLE
events.elapsed in half-time is broken

### ISSUE THREAD

**Issue by tiagoafonso85** [marcoblume/pinnacle.API#16]
Hi shapenaji,

Why the time (sports.leagues.events.elapsed) received from GetInrunning () is spoiled, in half-time? The time appears with the value with which it ended at the end of the first part, and not changes ...
At the half-time it should  start at 0 again until 15

Thanks

**Comment by shapenaji** [comment]
Hi tiago, 

Unfortunately, I don't have an answer for that, it's coming from the API and not from the wrapper. Inrunning State just says the number of elapsed minutes in the match.

If there's a bug in that, you should let pinnacle know through customer service.
