### ISSUE TITLE
 "LINE_CHANGED" error when placing bet

### ISSUE THREAD

**Issue by ractingmatrix** [marcoblume/pinnacle.API#18]
Hello

I often run into this error. Is there any way to avoid it , such as choosing to accept whatever line? Or is there a quick way to obtain the latest line, given eventsid?

Thanks in advance.

Regards
Ma

**Comment by shapenaji** [comment]
There an option to accept better line (this is default behavior), but there's no accept worse line. (Given that the line could move hugely from one point to another, this is almost certainly safer. It might be worth sending a message to pinnacle and requesting that kind of functionality though, allowing you to set a maximum price)

**Comment by ractingmatrix** [comment]
Thanks for the reply.
