### ISSUE TITLE
GetBetsList()

### ISSUE THREAD

**Issue by arrabella** [marcoblume/pinnacle.API#19]
Hi, I have just tried to use the GetBetsList function to get settled bets and there is an error returning the values. I have tried using different start and end date values, along with the default as per the documentation example. 

Here is an example of the error received:
> results <- GetBetsList()
No encoding supplied: defaulting to UTF-8.
Error in data.frame(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  : 
  arguments imply differing number of rows: 0, 3

Thanks in advance for any assistance.

**Comment by shapenaji** [comment]
Hi arrabella

Sorry for the delay.

Unfortunately, I can't seem to reproduce that error, can you post the output of:

`sessionInfo()`

and

`packageVersion('pinnacle.API')`?

**Comment by arrabella** [comment]
Hi shape,

Just tried to get the bet list and received the same error. The output of the session info and version are as follows:

> packageVersion('pinnacle.API')
[1] ‘2.0.9’

> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.6 (unknown)
locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] pinnacle.API_2.0.9
loaded via a namespace (and not attached):
 [1] httr_1.2.1        rjson_0.2.15      plyr_1.8.4        magrittr_1.5      R6_2.2.0         
 [6] tools_3.2.1       curl_2.6          Rcpp_0.12.10      uuid_0.1-2        data.table_1.10.4
[11] jsonlite_1.4      openssl_0.9.6     purrr_0.2.2

Thanks, A

**Comment by shapenaji** [comment]
Huh, that's quite an old version of R, I don't think I ever tested on anything that old, and I'm not sure if it will be easy to keep backwards-compatible going forwards.

Can you try updating your R version? or will it break things?

**Comment by arrabella** [comment]
Apologies for the delay. I'm just making sure there will be no issues, then updating the version of R. It should be done later today.

**Comment by arrabella** [comment]
I've updated R now to the latest version. I am now getting the following error:
> results <- GetBetsList()
No encoding supplied: defaulting to UTF-8.
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 0, 4, 3
In addition: Warning message:
'jsonlite::rbind.pages' is deprecated.
Use 'rbind_pages' instead.
See help("Deprecated") 

The new session info is as follows:
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6
Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] pinnacle.API_2.0.9
loaded via a namespace (and not attached):
 [1] httr_1.3.1        compiler_3.4.1    rjson_0.2.15      plyr_1.8.4       
 [5] magrittr_1.5      R6_2.2.2          tools_3.4.1       curl_2.8.1       
 [9] Rcpp_0.12.12      uuid_0.1-2        data.table_1.10.4 jsonlite_1.5     
[13] rlang_0.1.2       openssl_0.9.6     purrr_0.2.3   

Thanks, A

**Comment by shapenaji** [comment]
can you try the dev version?

`devtools::install_github('marcoblume/pinnacle.API')`

you might need to install devtools first (just `install.packages('devtools')`)

**Comment by arrabella** [comment]
Hi,

I've just checked this again and it seems to work now. There is still the following warning message, but the data is available through the API. 
Warning message:
'jsonlite::rbind.pages' is deprecated.
Use 'rbind_pages' instead.
See help("Deprecated") 

Apologies for the delay in response. I believe this issue can be closed now. 

Thanks, A
