### ISSUE TITLE
Issue with Events with multiple IDs

### ISSUE THREAD

**Issue by fur81z14** [marcoblume/pinnacle.API#2]
Hi,

I am using PinnacleWrapper for .NET and it seems it is going obsolete, because I found multiple issues there. I hope you can help me with the API. Is there some more info about bet status I and bet status O. The problem is that I am finding a correct Line ID for some bet with iteration through the events got from GetFixtureEvents, but then if I try to place the bet with that LineID and its EventID (not always) I am getting Bad Request (Error 400). In such cases I found that this is related to the Events marked by status = I.
Also, another issue that I found is that TeamTotals bets are not available in .NET wrapper. However, I deserialized the JSON request and I got the bets well, but then I realized that there is NO LineID nor AltLineID for these bets. Is there anything special about placing these kind of bets.

Thanks in advance...

**Comment by ghost** [comment]
Sorry, we can't help you with the PinnacleWrapper, as we are not maintaining it.

You can read  more about the event statuses in our manual http://www.pinnaclesports.com/en/api/manual#EVENT_STATUS

When you get the 400 error, check the body of the response, it will show the actually error message.

You can also check the section how to place a straight bet
http://www.pinnaclesports.com/en/api/manual#getting-started

Good luck!
