### ISSUE TITLE
Limited odds

### ISSUE THREAD

**Issue by tiagoafonso85** [marcoblume/pinnacle.API#20]
Hi Shape, 
All the odds obtained through the wrapper get only the odds for a single number of points, instead of getting all the available odds for several point numbers, just like the api manual says on the pinnacle website that does.
Ex:
Https://www.pinnacle.com/de/api/manual#GetOdds

In the wrapper, just give for example, for "totals":

Leagues.events.periods.totals.points leagues.events.periods.totals.over
1 .....................................2.75        ..............................................1.892

   Leagues.events.periods.totals.under leagues.events.periods.totals.altLineId
1   .....................................2,010                 ................................. NA

Where altLineId always has the NA value in all games, when I think I should have the Id associated with the number of points in question ...

**Comment by shapenaji** [comment]
Hi tiago,

they're actually there, but you have to opt-in to how you get them, the `tableformat` argument is there for that reason.

By default, GetOdds returns mainlines, but you can choose other table formats:


'mainlines' (default), only shows mainlines
'long' for a single record for each spread/total on an event, 
'wide' for all lines as one record, 
'subtables' all lines for spreads/totals stored as nested tables

**Comment by tiagoafonso85** [comment]
Hehe
My fault, sorry

Thanks
