### ISSUE TITLE
Lexical error when accessing the API

### ISSUE THREAD

**Issue by astrofaz** [marcoblume/pinnacle.API#23]
Hi,

recently my automated code to access the Pinnacle API has been failing. Debugging it line by line produced the following error when using the GetBetsList() and showOddsDF() functions:

```
Error: lexical error: invalid char in json text.
                                       <!doctype html public "-//w3c//
                     (right here) ------^

```

According to posts I found on Stackoverflow (https://stackoverflow.com/questions/41000112/reading-a-json-file-in-r-lexical-error-invalid-char-in-json-text) this seems to be related to issues with the jsonlite package. I've updated all the required packages as well as the latest version of pinnacle.API from Github but the error persists.

Below is the output from sessionInfo():

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pinnacle.API_2.3.2  magrittr_1.5        purrr_0.2.4         uuid_0.1-2         
[5] jsonlite_1.5        httr_1.3.1          data.table_1.10.4-3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14    lattice_0.20-35 withr_2.1.0     digest_0.6.13   grid_3.4.3     
 [6] R6_2.2.2        plyr_1.8.4      git2r_0.19.0    rlang_0.1.4     curl_3.1       
[11] Matrix_1.2-12   devtools_1.13.4 rjson_0.2.15    tools_3.4.3     compiler_3.4.3 
[16] memoise_1.1.0   openssl_0.9.9 
```

Thanks,

Sean

**Comment by shapenaji** [comment]
Hi astrofaz,

Usually that's an issue when the api does not return a json response, but instead returns html. 
Typically it's an issue with location. Some locations are geoip blocked.  can you try:

```
library(pinnacle.API)
SetCredentials()
pinnacle.API:::APIcall('/v2/sports')
```

and see what the response you get is?

**Comment by Mangiafuoco** [comment]
From what hosting provider you are calling API?

**Comment by astrofaz** [comment]
Thanks Shape and Mangiafuoco for your responses. I'm currently travelling so am changing ISP on a regular basis. I experimented with using a VPN and the problem disappeared, so it looks like Shape was right on the money. Thanks!

**Comment by Mangiafuoco** [comment]
Yes, if Your geolocation is banned your will receive html page with information about restricting instead json data.
