### ISSUE TITLE
Wrong Odds In API

### ISSUE THREAD

**Issue by SportspunterDotCom** [marcoblume/pinnacle.API#3]
We seem to have occasional api problems, particularly with tennis.

For example earlier today we had these odds for Smyczek/Dzumhur:
                     {
                        "altLineId" : 122189343,
                        "over" : 2.15,
                        "points" : 22.5,
                        "under" : 1.735
                     },

Whereas the real odds were o22.5 @ 1.793

The odds were incorrect for quite a long time now (at least 1/2 an hour since I woke up, so possibly a lot longer)

thanks

**Comment by ghost** [comment]
Hi, 
Please contact our Customer Service Department csd@pinnaclesports.com for these kind of issues.
Thanks

**Comment by SportspunterDotCom** [comment]
Hello, I did contact the customer service department, and they gave me this response:  The "click here" was for github.

 Dear Client,

Thank you for the email regarding your API experience.

We are sorry, but while we appreciate any and all feedback, we do not offer technical support or instructions beyond the available API manual.

We consistently work to keep this manual updated as best possible, to ensure only current and relevant information is available.

If you run into any problems with the functions contained in the pinnacle.API package, we recommend you please click here for more information.

We apologize for any inconvenience caused.
