### ISSUE TITLE
GetLine error

### ISSUE THREAD

**Issue by tiagoafonso85** [marcoblume/pinnacle.API#34]
GetLine(sportid=29,leagueids=196742, eventid=832766555, periodnumber = 0,  betType="Moneyline")

2018-03-28 23:26:34| Pulling line - sportid: 29 leagueids: 196742 eventid: 832766555 betType: Moneyline oddsFormat: AMERICAN
Error in ifelse(endsWith(response$message, "."), "", ".") : 
  could not find function "endsWith"

**Comment by tiagoafonso85** [comment]
I have already updated my version of R.
No error returned yet.

**Comment by shapenaji** [comment]
Thanks tiago, 
If you don't mind me asking, which version of R were you on before? so we can add that as a requirement to the package.

**Comment by tiagoafonso85** [comment]
Before: R version 3.2.5
Now: R version 3.4.4
