### ISSUE TITLE
How get results of bets who was with pending acceptance?

### ISSUE THREAD

**Issue by tiagoafonso85** [marcoblume/pinnacle.API#38]
Hello Shape,
After we do a bet, if the bet stay with pending accpetance, how we can know after, if the bet was accepted with the uniqueRequestId ? The wrapper doesn't permit this, unlike pinnacle's API.

Do you think we should be untangle ourselves instead of coming to question about every complication we have with the wrapper?

I think I've taken your contribution, as a payed work of the pinnacle, to continue developing the wrapper (which I think is theirs because the author is Marco Blume).  If I'm wrong, excuse my exaggeration about issues around the wrapper ...

Thanks

**Comment by shapenaji** [comment]
Hi Tiago, 

In answer to your question, I believe there needs to be support for that endpoint, and you're welcome to contribute!

The wrapper is not an official pinnacle product, see terms and conditions. While some folks like Marco are associated with pinnacle, this package was always intended to be a starting point for working with the API. Something we use ourselves.

Pinnacle's API continues to be in development and it is possible that this package will not be up to date with their endpoints.

As evidenced by our Terms and by our license, we are not a commercial product. But we do strive to keep it working.

Regarding your issues with the package, I'm not sure I understand your last point.

Regarding your recently opened issues:

The intermittent nature of your erros you're getting in the other thread appear to be either network related or pinnacle related, specifically the internal error. And we don't have a way to reproduce your error. (We have fixed all those we were able to reproduce)

If there are problems in the pinnacle API, you should contact their customer service.

As many other projects on github, If you see an issue or an area of improvement here you can open a pull request with a fix.

**Comment by tiagoafonso85** [comment]
The internal error, I sent to the customer service, and they replied that they would fix it.

Betting on Events with Live Delay
Bets placed on events with live delay are treated differently than other bets. They get betId assigned only once they are ACCEPTED.

The only way to find out the status of such a bet is by querying Get Bets V2 by uniqueRequestIds:
/v2/bets?uniqueRequestIds=86a90ab9-fca1-4703-a11c-ce329a85584e

how we can do querying Bets V2 by uniqueRequestIds, for the bets with Status = "PENDING_ACCEPTANCE" ?

Now I understand the terms better.
I am very grateful for your contribution to the wrapper. It's extra useful to me.

I am not a computer scientist, but I can strive to learn.
If I can contribute something useful to the wrapper, I'll do it.

Thanks a lot Shape.

**Comment by shapenaji** [comment]
You're welcome! I'll see what we can do about that endpoint' it seems like a fairly straightforward one
