### ISSUE TITLE
Functions returning empty dataframes

### ISSUE THREAD

**Issue by GKyle23** [marcoblume/pinnacle.API#4]
Hi there,

When I call functions such as `GetSports()` or `GetCurrencies()` I get empty dataframes.

**Comment by marcoblume** [comment]
C/P the code please

**Comment by jmonez** [comment]
I think this might be an issue of not throwing an error for invalid credentials with these methods: 

> SetCredentials("INVALIDUSER","INVALIDPW")
> AcceptTermsAndConditions(accepted=TRUE)
> GetSports()
> data frame with 0 columns and 0 rows

For other methods authentication fail errors are thrown: 

> SetCredentials("INVALIDUSER","INVALIDPW")
> AcceptTermsAndConditions(accepted=TRUE)
> GetClientBalance()
> $code
> [1] "FORBIDDEN"

$message
[1] "Authorization failed, please supply a valid customer ID and password."

**Comment by elementmike** [comment]
Hi, GKyle23.

Did you find the source to your problem?

I am receiving "Authorization failed, please supply a valid customer ID and password", too.

Just like jmonez said.

Thank you in advance!

**Comment by marcoblume** [comment]
The source seems to be that your customerID/password combination is not allowed to have access to the API. Contact pinnacle directly.
