### ISSUE TITLE
duplicate event ids for same fixture

### ISSUE THREAD

**Issue by badarkace** [marcoblume/pinnacle.API#40]
Occasionally there are duplicate event ids with corresponding odds for the same fixture in live mlb baseball with the only difference being the status. H,I or O. Can anyone tell me which of the event ids is the correct line? how do i tell if the line has gone offline using the since parameter?

**Comment by shapenaji** [comment]
From here:
https://pinnacleapi.github.io/linesapi#operation/Fixtures_V1_Get

```

status | string"O""H""I"Status of the event.O = This is the starting status of a game. It means that the lines are open for betting, H = This status indicates that the lines are temporarily unavailable for betting, I = This status indicates that one or more lines have a red circle (lower maximum bet amount)
-- | --

```

You use the lineid (and not the EventID) to wager, so they should have distinct lineids, are those different?

**Comment by shapenaji** [comment]
Closing. If there's any other issue, please re-open
