### ISSUE TITLE
"NO_API_ACCESS","message":"Account not permitted to access the API"

### ISSUE THREAD

**Issue by tiagoafonso85** [marcoblume/pinnacle.API#41]

**Comment by Cashmereee** [comment]
You need to have money in your pinnacle account to access the api

**Comment by tiagoafonso85** [comment]
Hi cashmereee, the Access to the API was interdicted by Pinnacle. Now the API os only for another bookmakers who want to use odds from Pinnacle in your bookmaker.

**Comment by shapenaji** [comment]
Not in scope here. We don't control Pinnacle's access rules.
