### ISSUE TITLE
Tennis Scoring

### ISSUE THREAD

**Issue by JohnnyBlazzing** [marcoblume/pinnacle.API#43]
I have noticed the scoring for tennis games is a total of games won, which means the winner does not necessarily has the highest points.

I think for a Tennis Match bet... the score should be the no# of sets won, as the winner is the player with the most sets - not the most game points. So womens would have a max value of 2, and mens 3.

And for game bets eg '<PlayerName> Game 13 of Set 1', the scores should be for the game with values 0,15,30,40,50. not the number of games they have won in the match so far.

The only tennis bets where number of games do count is Set bets, Eg '<PlayerName> To Win Set 2' so keep this as is.

**Comment by shapenaji** [comment]
Not in the scope of this package. This package is just for interacting with the API that Pinnacle supplies.
