### ISSUE TITLE
oddsRequest stopped working

### ISSUE THREAD

**Issue by valnech** [marcoblume/pinnacle.API#5]
From today's morning 13/06/2016 I receive the following error for odds request

/v1/odds?sportid=34&since=310198712

{"code":"INVALID_REQUEST_DATA","message":"Missing exchange rate for currency USD , for CustomerId XXX\r\nParameter name: oddsRequest"}

**Comment by shapenaji** [comment]
This was a long time back, but I'm not sure if your problem was solved, (I believe it should have been, since this looks like an issue with pinnacle's API and not the R wrapper), I'm closing for now, let me know if this needs to be reopened
