### ISSUE TITLE
showOddsDF

### ISSUE THREAD

**Issue by ractingmatrix** [marcoblume/pinnacle.API#6]
hi, is there a way to change to odds format to other format than the default American? thanks.

**Comment by shapenaji** [comment]
Currently the showOddsDF function does not support alternate formats, but it is a wrapper around `GetOdds`, `GetFixtures`, and `GetInrunning` functions, `GetOdds` does have alternate formats. I'll update showOddsDF as well.

**Comment by ractingmatrix** [comment]
thanks for the reply. look forward to the enhancement.

**Comment by shapenaji** [comment]
Heya, pushed a new version, install and try the following `showOddsDF(oddsformat = 'DECIMAL')`

**Comment by shapenaji** [comment]
Also, if there are any other odds formats you would prefer, I suggest the `odds.converter` package

**Comment by ractingmatrix** [comment]
thanks a lot for the quick enhancement and the suggestion!

**Comment by ractingmatrix** [comment]
Hi there,

Wondering if it's possible to use the api to place bets on matches
specified in a csv file. That is, I have a csv file that contains the
matches that I would like to bet on. I want to place bet automatically with
the api.

Thanks.
