### ISSUE TITLE
timeout 

### ISSUE THREAD

**Issue by ractingmatrix** [marcoblume/pinnacle.API#7]
hi, just wondering if there would be timeouts after executing SetCredentials. in other words, can i continue to run the API (having logged in using SetCredentials) as long as I want? thanks.

**Comment by ractingmatrix** [comment]
any idea?

**Comment by shapenaji** [comment]
SetCredentials just stores the Creds inside the loaded package memory. So they will continue to be available for as long as that R session persists. It will then use them on each request. (But you are not 'logged in' persay). Per the API manual, each request needs to be authenticated.

**Comment by ractingmatrix** [comment]
thank you for the reply.
