### ISSUE TITLE
showOddsDF merge error

### ISSUE THREAD

**Issue by TuomoNieminen** [marcoblume/pinnacle.API#8]
Hi,

Thank you for providing this wrapper for the Pinnacle API.  I tried the following:

`odds <- pinnacle.API::showOddsDF(29, oddsformat = "AMERICAN")`

And got this error.

```
Error in merge.data.table(., inrunning[sports.id %in% sportid], by.x = "leagues.events.id",  : 
  Elements listed in `by.y` must be valid column names in y.
```

I am using R 3.3.3 and pinnacle API 2.0.4

**Comment by shapenaji** [comment]
Hello!

This has been fixed as of v2.0.5 here on github.

You can install with the devtools package,

`devtools::install_github('marcoblume/pinnacle.API')`

Not yet on CRAN however

**Comment by shapenaji** [comment]
(The problem emerges if there is no Live Soccer Available) 

I'll keep this open to see if this solves your problem

**Comment by TuomoNieminen** [comment]
Yes the development version seems to fix the problem for me. Thank you.
