### ISSUE TITLE
showOddsDF(tableformat = 'wide')

### ISSUE THREAD

**Issue by arrabella** [marcoblume/pinnacle.API#9]
Hi,

Thank you for providing this wrapper for the Pinnacle API. I tried the following:
`df <- showOddsDF(29,tableformat = 'wide')`
And I get this error:
`Error: Don't know how to convert NULL into a function`

All the other table formats work fine. 

Thanks

**Comment by shapenaji** [comment]
Hi arrabella

Reproduced the issue and fixed as of 2.0.6. There was some missing functionality for the wide data format.

Let me know if that works for you and then
we'll get it pushed over to CRAN as soon as we can.

**Comment by arrabella** [comment]
Hi shapenaji, 

Thanks very much for the quick fix. Was the change on CRAN already or available in the development version? 

Thanks

**Comment by shapenaji** [comment]
Still in the dev version, 

devtools::install.packages('marcoblume/pinnacle.API') for now

**Comment by arrabella** [comment]
That's great. Thanks for fixing!
